{% set name = "python-fsutil" %}
{% set version = "0.9.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/python-fsutil-{{ version }}.tar.gz
  sha256: a4607838e33adcb63e5bc3cf918e9ef32f816ff41e73112d6a34365994577448

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - python >=3.5
    - requests

test:
  imports:
    - fsutil
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/fabiocaccamo/python-fsutil
  summary: file-system utilities for lazy devs.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - pmrowla
    - efiop
    - shcheklein
    - fabiocaccamo
