{% set name = "python-fsutil" %}
{% set version = "0.8.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/python-fsutil-{{ version }}.tar.gz
  sha256: c95f2187ac2f4c041c36a97e1a6457d595d3e3a3badc24a26f014f716f444b5b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - python >=3.5
    - requests

test:
  imports:
    - fsutil
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/fabiocaccamo/python-fsutil
  summary: file-system utilities for lazy devs.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - pmrowla
    - efiop
    - shcheklein
    - fabiocaccamo
